//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica_02_crud_desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.EMPLEADO_SUCURSAL = new HashSet<EMPLEADO_SUCURSAL>();
            this.SUCURSAL = new HashSet<SUCURSAL>();
        }
    
        public long PERSONA_ID { get; set; }
        public System.DateTime EMPLEADO_FECHAINGRESO { get; set; }
        public Nullable<System.DateTime> EMPLEADO_FECHASALIDA { get; set; }
        public decimal EMPLEADO_SALARIO { get; set; }
        public string EMPLEADO_CARGO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO_SUCURSAL> EMPLEADO_SUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUCURSAL> SUCURSAL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
