//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica_02_crud_desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO_SUCURSAL
    {
        public long PERSONA_ID { get; set; }
        public long SUCURSAL_ID { get; set; }
        public System.DateTime EMPSUC_FECHAINGRESO { get; set; }
        public Nullable<System.DateTime> EMPSUC_FECHASALIDA { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
