//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica_02_crud_desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public long PERSONA_ID { get; set; }
        public string PERSONA_CEDULA_RUC { get; set; }
        public string PERSONA_NOMBRES { get; set; }
        public string PERSONA_APELLIDOS { get; set; }
        public System.DateTime PERSONA_FECHANACIMIENTO { get; set; }
        public string PERSONA_DIRECCION { get; set; }
        public string PERSONA_TELEFONO { get; set; }
        public string PERSONA_EMAIL { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual SOCIO SOCIO { get; set; }
    }
}
