//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica_02_crud_desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIO()
        {
            this.CUENTA = new HashSet<CUENTA>();
        }
    
        public long PERSONA_ID { get; set; }
        public Nullable<long> SUCURSAL_ID { get; set; }
        public Nullable<long> USU_PERSONA_ID { get; set; }
        public System.DateTime SOCIO_FECHAEMISION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTA> CUENTA { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
