//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica_02_crud_desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_TRANSACCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_TRANSACCION()
        {
            this.TRANSACCION = new HashSet<TRANSACCION>();
        }
    
        public int TTRANSACCION_ID { get; set; }
        public string TTRANSACCION_DESCRIPCION { get; set; }
        public int TTRANSACCION_FACTOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCION { get; set; }
    }
}
