//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica_02_crud_desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        public long TRANSACCION_ID { get; set; }
        public Nullable<long> CUENTA_ID { get; set; }
        public Nullable<long> SUCURSAL_ID { get; set; }
        public Nullable<int> TTRANSACCION_ID { get; set; }
        public Nullable<long> PERSONA_ID { get; set; }
        public System.DateTime TRANSACCION_FECHA { get; set; }
        public decimal TRANSACCION_MONTO { get; set; }
        public string TRANSACCION_REFERENCIA { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
